eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka
      instence:
      preferIpAddress: true
spring:
  application:
    name: AdityaEurekaclient       
      
      
    
